apiVersion: v1
kind: Service
metadata:
  name: "{{  .Chart.Name }}-service"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.containerPort }}
  selector:
    app: {{  .Chart.Name }}
