apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{  .Chart.Name }}-deployment"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas:  {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: {{  .Chart.Name }}
    spec:
     containers:
      - name: {{  .Chart.Name  }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: VCAP_APPLICATION
            valueFrom:
              secretKeyRef:
                name: "{{  .Chart.Name }}-secret"
                key: VCAP_APPLICATION
          - name: VCAP_SERVICES
            valueFrom:
              secretKeyRef:
                name: "{{  .Chart.Name }}-secret"
                key: VCAP_SERVICES
          - name: WATSON_SPEECH_TO_TEXT
            valueFrom:
              secretKeyRef:
                name: "{{  .Chart.Name }}-secret"
                key: WATSON_SPEECH_TO_TEXT
          - name: WATSON_VISUAL_RECOGNITION
            valueFrom:
              secretKeyRef:
                name: "{{  .Chart.Name }}-secret"
                key: WATSON_VISUAL_RECOGNITION
        ports:
        - containerPort: {{ .Values.service.containerPort }}
