---
apiVersion: v1
kind: Secret
metadata:
  name: "{{  .Chart.Name }}-secret"
type: Opaque
data:
  VCAP_APPLICATION: {{  .Values.secrets.VCAP_APPLICATION }}
  VCAP_SERVICES: {{  .Values.secrets.VCAP_SERVICES }}
  WATSON_SPEECH_TO_TEXT: {{  .Values.secrets.WATSON_SPEECH_TO_TEXT }}
  WATSON_VISUAL_RECOGNITION: {{  .Values.secrets.WATSON_VISUAL_RECOGNITION }}
